--- 
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t public.ecr.aws/g3p1a4w6/node-pipeline ."
      - "docker tag public.ecr.aws/g3p1a4w6/node-pipeline public.ecr.aws/g3p1a4w6/node-pipeline:latest"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push public.ecr.aws/g3p1a4w6/node-pipeline:latest"
  pre_build: 
    commands: 
      - "echo Logging in to Docker Hub..."
      - "docker login --username=\"dvohra\" --password=\"password\""
version: 0.1

