--- 
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t node-pipeline ."
      - "docker tag node-pipeline 000965729629.dkr.ecr.us-east-1.amazonaws.com/node-pipeline
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push 000965729629.dkr.ecr.us-east-1.amazonaws.com/node-pipeline"
  pre_build: 
    commands: 
      - "echo Logging in to Docker Hub..."
      - "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 000965729629.dkr.ecr.us-east-1.amazonaws.com"
version: 0.1

