--- 
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t node-pipeline ."
      - "docker tag node-pipeline public.ecr.aws/g3p1a4w6/node-pipeline:latest"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push public.ecr.aws/g3p1a4w6/node-pipeline:latest"
  pre_build: 
    commands: 
      - "echo Logging in to Docker Hub..."
      - "aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws"
version: 0.1

